### ISSUE TITLE
ci: automate releases

### ISSUE THREAD

**Issue by DonIsaac** [DonIsaac/oxbuild#15]
Automate release to crates.io.

## Questions
- Should we manually make a release on GitHub, then have it deply to crates.io?
- Should we just make a PR bumping the version, then have a CI job automatically create a release (to GH/crates.io)?

**Comment by ashleygwilliams** [comment]
i've currently set it up to publish on tag push, but there's a few other mechanisms we can use instead (manual dispatch and push to branch). overall i would say that tag push is the most common one we see, generally.

**Comment by DonIsaac** [comment]
#26

**Comment by ashleygwilliams** [comment]
happy to keep collaborating here but if you want something slightly more sync- feel free to join our discord :) https://discord.gg/7kC6f7j2

**Comment by DonIsaac** [comment]
@ash

> happy to keep collaborating here but if you want something slightly more sync- feel free to join our discord :) https://discord.gg/7kC6f7j2

Just joined
