### ISSUE TITLE
publish `oxbuild` to NPM

### ISSUE THREAD

**Issue by DonIsaac** [DonIsaac/oxbuild#17]

**Comment by ashleygwilliams** [comment]
https://opensource.axo.dev/cargo-dist/book/installers/npm.html to finish out #20 you'll just need to follow these instructions :)

**Comment by DonIsaac** [comment]
@ashleygwilliams thanks a ton! Can it handle cargo releases as well?

**Comment by ashleygwilliams** [comment]
hey! so it can, but we have not built it in yet as we want to make sure we can handle the "publish cascade" for linked monorepos appropriately. you can use a custom publish job tho- which you could steal wholesale from how cargo-dist does it for itself here: https://github.com/axodotdev/cargo-dist/blob/main/.github/workflows/publish-crates.yml

(i am happy to make a PR for this if you are interested!)

**Comment by ashleygwilliams** [comment]
totally understood, i'll make a PR some time today with the npm and crates.io publishing - i'll leave some instructions for the secrets set up you'll need to do :)

**Comment by DonIsaac** [comment]
I've got the secrets set up - `CRATES_TOKEN` and `NPM_TOKEN` respectively. I've got a draft for crates.io releases here: #26 mind giving it a review?

Also, thanks for all your help!

**Comment by ashleygwilliams** [comment]
looking!
